# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('alumni_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=20, null=True)),
                ('dept_code', models.CharField(max_length=7)),
                ('grad_year', models.IntegerField()),
                ('cgpa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.Alumnus')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus_majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.Alumnus')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=15)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.Company')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.Alumnus')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni_tracker.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Studied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=50)),
                ('grad_year', models.IntegerField()),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.Alumnus')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_tracker.School')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni_tracker.Location'),
        ),
        migrations.AddField(
            model_name='alumnus',
            name='present_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni_tracker.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='studied',
            unique_together=set([('roll_no', 'school_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('roll_no', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='alumnus_majors',
            unique_together=set([('roll_no', 'major')]),
        ),
        migrations.AlterUniqueTogether(
            name='alumnus_links',
            unique_together=set([('roll_no', 'link')]),
        ),
    ]
