# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='dept_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni_tracker.Department'),
        ),
    ]
